"""Generate TypedDict models from the OpenAPI 3.0 schema a service serves.

    python -m vexxhost_clientcore.codegen \\
        --service budget \\
        --spec https://budget.example/openapi-3.0.yaml \\
        --output budgetclient/v1/models.py

--spec may also be a local file. The generated module ends with
SPEC_VERSION, the server build named by the schema's info.version, so a
client records which deployment its models describe.

The generator runs through uvx at a pinned version, so every client gets the
same output for the same schema. Set DATAMODEL_CODEGEN to override the
command, for example to a datamodel-codegen already on PATH.
"""

import argparse
import os
import re
import shlex
import subprocess
import sys
import tempfile
import urllib.request

GENERATOR = "uvx --from datamodel-code-generator==0.83.0 datamodel-codegen"
OPTIONS = [
    "--input-file-type", "openapi",
    "--output-model-type", "typing.TypedDict",
    "--target-python-version", "3.10",
    "--use-standard-collections",
    "--use-union-operator",
    "--no-use-closed-typed-dict",
    "--disable-timestamp",
    "--formatters", "builtin",
]  # fmt: skip


def spec_version(text):
    """Return info.version from a YAML OpenAPI document, without a YAML parser."""
    in_info = False
    for line in text.splitlines():
        if line.startswith("info:"):
            in_info = True
        elif in_info and re.match(r"\S", line):
            break
        elif in_info:
            match = re.match(r"  version:\s*['\"]?([^'\"\s]+)", line)
            if match:
                return match.group(1)
    raise ValueError("the schema has no info.version")


def fetch(spec):
    if re.match(r"https?://", spec):
        with urllib.request.urlopen(spec, timeout=30) as response:
            return response.read().decode()
    with open(spec, encoding="utf-8") as f:
        return f.read()


def generate(service, spec, output):
    text = fetch(spec)
    version = spec_version(text)
    command = shlex.split(os.environ.get("DATAMODEL_CODEGEN", GENERATOR))
    header = (
        f"# Code generated by vexxhost_clientcore.codegen from the schema "
        f"{service} {version} serves. DO NOT EDIT."
    )
    with tempfile.NamedTemporaryFile("w", suffix=".yaml") as f:
        f.write(text)
        f.flush()
        subprocess.run(
            [
                *command,
                "--input", f.name,
                "--output", output,
                *OPTIONS,
                "--custom-file-header", header,
            ],
            check=True,
        )  # fmt: skip
    with open(output, "a", encoding="utf-8") as f:
        f.write(
            f"\n# The {service} build whose served schema these models were "
            f'generated from.\nSPEC_VERSION = "{version}"\n'
        )
    return version


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--service", required=True, help="e.g. budget")
    parser.add_argument("--spec", required=True, help="URL or file")
    parser.add_argument("--output", required=True, help="models.py path")
    args = parser.parse_args(argv)
    version = generate(args.service, args.spec, args.output)
    print(f"generated {args.output} from {args.service} {version}")


if __name__ == "__main__":
    sys.exit(main())
